---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: ocp1m0w-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin-sa
    namespace: ocp1m0w-b
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: copy-pull-secret-
  namespace: ocp1m0w-b
spec:
  template:
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
      - name: copier
        image: quay.io/ocp-edge-qe/cli
        command: ["/bin/bash", "-c"]
        args:
          - |
            oc -n openshift-config get secret pull-secret -ojson |jq 'del(.metadata.namespace, .metadata.uid, .metadata.resourceVersion, .metadata.creationTimestamp, .metadata.selfLink, .metadata.annotations, .metadata.ownerReferences) |.metadata.namespace = "ocp1m0w-b"' |oc apply -f -
            oc -n openshift-config get secret bmc-secret -ojson |jq 'del(.metadata.namespace, .metadata.uid, .metadata.resourceVersion, .metadata.creationTimestamp, .metadata.selfLink, .metadata.annotations, .metadata.ownerReferences) |.metadata.namespace = "ocp1m0w-b"' |oc apply -f -
      restartPolicy: OnFailure
  backoffLimit: 3
